### PR TITLE
Fix test_KinematicSimulationTrajectoryExecutor

### LINKED ISSUE #126: test_KinematicSimulationTrajectoryExecutor sometimes fail
It seems the success of `test_KinematicSimulationTrajectoryExecutor` is not deterministic.

### PR DESCRIPTION
**Pull request by jslee02**
`KinematicSimulationTrajectoryExecutorTest.execute_TrajectoryIsAlreadyRunning_Throws` test occasionally fails because the result is non-deterministic. This PR fixes the test to take into account the case as well.

Resolves #126

### CODE REVIEW

**Comment by gilwoolee** [comment]
Oh haha this makes total sense!!! Thanks for looking into this @jslee02 !

File: tests/control/test_KinematicSimulationTrajectoryExecutor.cpp [hunk 1]
```diff
@@ -155,14 +155,23 @@ TEST_F(KinematicSimulationTrajectoryExecutorTest, execute_TrajectoryIsAlreadyRun
...
+  try
+  {
+    executor.execute(mTraj);
+  }
+  catch (const std::runtime_error& e)
+  {
+    EXPECT_EQ(std::string(e.what()), "Another trajectory in execution.");
+
+    // It could not have finished the trajectory execution yet.
+    EXPECT_NE(mSkeleton->getDof(0)->getPosition(), 1.0);
```
Comment (gilwoolee) [inline tests/control/test_KinematicSimulationTrajectoryExecutor.cpp]: Does this always hold? What if the other thread finished the execution of line 156 by the time we got here?

Comment (jslee02) [inline tests/control/test_KinematicSimulationTrajectoryExecutor.cpp]: > Does this always hold?

It does not. :sob: I thought detached threads are immediately killed when the main thread throw an exception, which is totally not true. If we add `std::this_thread::sleep_for(std::chrono::seconds(5));` at line 166, this test fails.

Let me remove this line.
